export const ROUTES = {
  HOME: "/",
  TARIFS: "/tarifs",
  RESSOURCES: "/ressources",
  CONNEXION: "/connexion",
  INSCRIPTION: "/inscription",
  AUTH_CALLBACK: "/auth/callback",
  DASHBOARD: "/tableau-de-bord",
  FACTURES: "/factures",
  FACTURE_NOUVELLE: "/factures/nouvelle",
  FACTURE_DETAIL: (id: string) => `/factures/${id}`,
  CLIENTS: "/clients",
  TRANSACTIONS: "/transactions",
  INBOX: "/boite-de-reception",
  TVA: "/declarations-tva",
  EXPORT: "/export-fiduciaire",
  ARCHIVE: "/archive",
  PAIE: "/paie",
  RAPPORTS: "/rapports",
  PARAMETRES: "/parametres",
  SUIVI_PAIEMENTS: "/suivi-paiements",
  RAPPROCHEMENT: "/rapprochement",
  SAISIE: "/saisie",
  FACTURE_PUBLIQUE: (shortId: string) => `/f/${shortId}`,
  COMPTABLE_PRO: "/comptable-pro",
  COMPTABLE_PRO_DOSSIERS: "/comptable-pro/dossiers",
  COMPTABLE_PRO_DOSSIER: (id: string) => `/comptable-pro/dossiers/${id}`,
  COMPTABLE_PRO_PARAMETRES: "/comptable-pro/parametres",
} as const;

export const LEGACY_ROUTES = {
  DASHBOARD: "/dashboard",
  FACTURES: "/invoices",
  FACTURE_NOUVELLE: "/invoices/new",
  INBOX: "/inbox",
  SETTINGS: "/settings",
  CONNEXION: "/auth/login",
  INSCRIPTION: "/auth/signup",
  TARIFS: "/pricing",
  TVA: "/tva",
  EXPORT: "/export",
} as const;
