export const ROUTES = {
  HOME: "/",
  TARIFS: "/tarifs",
  SOLUTIONS: "/#six-automatisations",
  RESSOURCES: "/ressources",
  CGU: "/cgu",
  CONFIDENTIALITE: "/confidentialite",
  CONNEXION: "/connexion",
  INSCRIPTION: "/inscription",
  MOT_DE_PASSE_OUBLIE: "/mot-de-passe-oublie",
  REINITIALISER_MOT_DE_PASSE: "/reinitialiser-mot-de-passe",
  INVITATION: (token: string) => `/invitations/${token}`,
  AUTH_CALLBACK: "/auth/callback",
  DASHBOARD: "/tableau-de-bord",
  FACTURES: "/factures",
  FACTURE_NOUVELLE: "/factures/nouvelle",
  FACTURE_DETAIL: (id: string) => `/factures/${id}`,
  CLIENTS: "/clients",
  TRANSACTIONS: "/transactions",
  INBOX: "/achats",
  RECEIPTS: "/notes-de-frais",
  TVA: "/declarations-tva",
  EXPORT: "/export-fiduciaire",
  ARCHIVE: "/archive",
  PAIE: "/paie",
  RAPPORTS: "/rapports",
  PARAMETRES: "/parametres",
  SUIVI_PAIEMENTS: "/suivi-paiements",
  TRESORERIE: "/tresorerie",
  RAPPROCHEMENT: "/rapprochement",
  SAISIE: "/saisie",
  ECRITURES: "/ecritures",
  ASSISTANT: "/assistant",
  FACTURE_PUBLIQUE: (shortId: string) => `/f/${shortId}`,
  COMPTABLE_PRO: "/comptable-pro",
  COMPTABLE_PRO_DOSSIERS: "/comptable-pro/dossiers",
  COMPTABLE_PRO_DOSSIER: (id: string) => `/comptable-pro/dossiers/${id}`,
  COMPTABLE_PRO_DOSSIER_DASHBOARD: (id: string) => `/comptable-pro/dossiers/${id}/tableau-de-bord`,
  COMPTABLE_PRO_DOSSIER_FACTURES: (id: string) => `/comptable-pro/dossiers/${id}/factures`,
  COMPTABLE_PRO_DOSSIER_ACHATS: (id: string) => `/comptable-pro/dossiers/${id}/achats`,
  COMPTABLE_PRO_DOSSIER_NOTES_DE_FRAIS: (id: string) => `/comptable-pro/dossiers/${id}/notes-de-frais`,
  COMPTABLE_PRO_DOSSIER_ECRITURES: (id: string) => `/comptable-pro/dossiers/${id}/ecritures`,
  COMPTABLE_PRO_PARAMETRES: "/comptable-pro/parametres",
} as const;

export const LEGACY_ROUTES = {
  AUTOMATISATIONS: "/automatisations",
  WORKFLOWS: "/workflows",
  DASHBOARD: "/dashboard",
  FACTURES: "/invoices",
  FACTURE_NOUVELLE: "/invoices/new",
  INBOX: "/inbox",
  SETTINGS: "/settings",
  CONNEXION: "/auth/login",
  INSCRIPTION: "/auth/signup",
  TARIFS: "/pricing",
  TVA: "/tva",
  EXPORT: "/export",
  RECEIPTS: "/receipts",
  CHAT: "/chat",
} as const;
